getPath: "C:/Users/Hacker/Downloads"
savePath: "C:/Program Files (x86)/CHJD/CHMT-36VA/Files"  
deleteSavedFiles: True 

easyedaRequiredColumns: 
  - Device 
  - Designator
  - X
  - Y
  - Rotation
  - Footprint
  - Value  

preferenceGroups:
- - SOT
  - SOP
  - QFN
  - TQFP

nozzleMap: 
  502:
    footprint: ['0402']   
    speed: 100
    checkVacuum: True
    useVision: True
  503:
    footprint: ['0603', SOD]  
    speed: 90
    checkVacuum: True
    useVision: True
  504:
    footprint: ['0805', '1206', SOT, UMAX, MSOP]  
    speed: 80
    checkVacuum: True
    useVision: True
  505:
    footprint: [SOP, SOIC, SMD-4]   
    speed: 70
    checkVacuum: True
    useVision: True
  506:
    footprint: [SMD-8, QFN, TQFP]  
    speed: 50
    checkVacuum: True
    useVision: True

feederMap:
  8:
    minStationId: 1
    maxStationId: 23
  12:
    minStationId: 23
    maxStationId: 27
  16:
    minStationId: 27
    maxStationId: 29
  24:
    minStationId: 29
    maxStationId: 30

noteMap: 
  capacitors: [footprint, value]
  diodes: [device, max volt, max current]
  ic: [device, footprint]
  led: [device, color]  
  resistors: [footprint, value]
  trans_mosfet: [device, footprint]

station:
  columns: [stationId, delt_x, delt_y, feedRate, note, height, speed, status, size_x, size_y, pullSpeed]
  default:
    size_x: 0
    size_y: 0
    delt_x: 0
    delt_y: 0

ecomponent:
  columns: [head, stationId, x, y, rotation, height, skip, speed, explain, note]
  default: {}

calib_point:
  columns: [x, y, note]
  default: {}